### ISSUE TITLE
toThrow improvements

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/earl#21]
`toThrow` is pretty limited now - it supports only full matching for error strings.

It should support following cases (from code):

```
// @todo: overloads like:
// .toThrow() throws anything
// .toThrow(/message/)
// .toThrow(ErrorClass)
// .toThrow(ErrorClass, 'message')
// .toThrow(ErrorClass, /message/)
// SINCE toThrow() is reserved for catching anything we need to do a extra work like for example: toThrow(expect.AUTOFIX)
```

**Comment by krzkaczor** [comment]
I not quite happy with this proposed API. Mainly because I wanted to avoid special syntax for autofix mode. Soft release has shown that the community finds it particularly interesting and it should be supported in the best way possible.

Requirements:
- autofixable
- similar API can be used for `rejectsWith`
- optimized for most popular usecases:
	- match by message (A)
    - match any error (B)
- supports throwing non errors

The main problem is that since it has to be autofixable we can't use simply `toThrow` to match any error case. What about:

`toThrow` mimics `toEqual` matching:

```typescript
.toThrow(expect.error("bye world")) // A
// expect.error supports multiple overrides like specified in the original post. 

// for B we have couple of options
.toThrow(expect.anything()) // already working
.toThrow(expect.a(Error))   // a little bit more specifc
.toThrow() // autofixes to leverage expect.error("msg")
```

I like this for multiple reasons. `toThrow` can leverage `smartEq` from `toEqual`, so users can leverage any already existing matchers. Autofix is very simple to implement since it just needs to handle special case to properly serialize errors (for now it would autofix to `.toThrow(expect.a(Error))`.

What I don't like about this is that most common case of matching only by error message (`.toThrow(expect.error("bye world"))`) is a little bit verbose so we could add helper validator like:

`toThrowError(...)` - alias to `.toThrow(expect.error(...))`

```typescript
.toThrowError('bye world')
.toThrowError(ErrorCls)
.toThrowError() // autofixes to .toThrowError('bye world')
```

**Comment by sz-piotr** [comment]
I like the `.toThrow(expect.error("bye world"))` syntax, I am however against sugar like `.toThrowError`, because it introduces more than one way to do things. Chai already has dozens of ways to express the same thing, let's not make it unnecessarily confusing.

That said, there is another problem. The type of the argument to `.toThrow` probably has to be `any`, because the matcher cannot return the correct type because of `toEqual`. So the following will compile just fine (but will be incorrect):
```ts
expect(() => {}).toThrow('message')
```

**Comment by krzkaczor** [comment]
Initial impl: https://github.com/krzkaczor/earl/pull/41

... I need to sleep on it

**Comment by krzkaczor** [comment]
Okay, reimplementation is done. 

@sz-piotr wanna implement missing overrides for `expect.error`? :->

**Comment by krzkaczor** [comment]
> I am however against sugar like `.toThrowError`, because it introduces more than one way to do things.

Oh, and just for the record: I am not against this as long as it's communicated clearly in docs that it's simply a convenience alias to `toThrow(expect.error())`. This allows us to maintain the consistent API for more complicated cases yet simple for most common.

This goes the same for all other matchers but can be implemented later (also community input would be great).

**Comment by krzkaczor** [comment]
Done by https://github.com/krzkaczor/earl/pull/45

`expect.error` has 2 overrides (with error msg or error cls and optional msg) and can be combined with other matchers (like `stringMatcher`) if it's required. http://localhost:3001/docs/api/api-reference#matchers

More docs incoming!
